version: '3.1'
services:
  backend:
    image: andersonvc/jirarrhea-backend:latest
    build: backend/.
    ports:
      - "3001:80"
    env_file:
      - ${HOME}/.openai/.env
  frontend:
    image: andersonvc/jirarrhea-frontend:latest
    build: frontend/.
    ports:
      - "3000:8080"
