version: '3'
services:
  web:
    image: andersonvc/jira-rrhea:latest
    networks:
      servenet:
        aliases:
          - app
    ports:
      - "5555:80"
  torch:
    image: pytorch/torchserve:latest-gpu
    volumes:
      - /model-server:/home/model-server
    ports:
      - "3000:8080"
      - "3001:8081"
    networks:
      servenet:
        aliases:
          - torch
networks:
  servenet:
    external:
      name: servenet
