version: '3'
services:
  backend:
    image: andersonvc/jirarrhea-backend:latest
    ports:
      - "3001:80"
  frontend:
    image: andersonvc/jirarrhea-frontend:latest
    ports:
      - "3000:8080"