apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-data
  namespace: jirarrhea
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  hostPath:
    path: /model-data
  storageClassName: development
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-data-pvc
  namespace: jirarrhea
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: development